dist: xenial
language: python
python:
  - "3.7"

# Command to install dependencies
install:
  - "pip install -r dev_requirements.txt"
  - "pip install coveralls"

# Command to run tests
script: 
  "coverage run --source lantern -m py.test"

after_success:
  coveralls
